### ISSUE TITLE
Add license

### ISSUE THREAD

**Issue by rbrijder** [bryangingechen/lean-matroids#1]
Please consider adding a Apache 2.0 license header to each lean file. This way other people could use the code to, say, try to merge it into mathlib.

[Nice work by the way!]

**Comment by bryangingechen** [comment]
Thanks! I'll try to do this later today.

**Comment by bryangingechen** [comment]
Closed in https://github.com/bryangingechen/lean-matroids/commit/6c41add661931169f1981e5368eca6cce4730cbf
